i52_ltpv_backend:
    resource: "@i52LTPVBackendBundle/Resources/config/routing.yml"
    prefix:   /administracion

i52_ltpv_frontend:
    resource: "@i52LTPVFrontendBundle/Resources/config/routing.yml"
    prefix:   /caja

app:
    resource: @AppBundle/Controller/
    type:     annotation

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
