diario:
    path:     /index
    defaults: { _controller: "i52LTPVBackendBundle:Diario:index" }

diario_show:
    path:     /{id}/show
    defaults: { _controller: "i52LTPVBackendBundle:Diario:show" }



